---
- name: Play to add ip address to the interface.
  hosts: all
  
  tasks:
  - name: cofiguring interface
    cisco.ios.ios_config:
    lines:
    - ip address dhcp
    parents: interface FastEthernet1/0
